# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TabWidget(object):
    def setupUi(self, TabWidget):
        TabWidget.setObjectName(_fromUtf8("TabWidget"))
        TabWidget.resize(596, 513)
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.cari = QtGui.QLineEdit(self.tab)
        self.cari.setObjectName(_fromUtf8("cari"))
        self.horizontalLayout.addWidget(self.cari)
        self.cari_warga = QtGui.QPushButton(self.tab)
        self.cari_warga.setObjectName(_fromUtf8("cari_warga"))
        self.horizontalLayout.addWidget(self.cari_warga)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.nasabah_list = QtGui.QTableWidget(self.tab)
        self.nasabah_list.setObjectName(_fromUtf8("nasabah_list"))
        self.nasabah_list.setColumnCount(0)
        self.nasabah_list.setRowCount(0)
        self.verticalLayout_4.addWidget(self.nasabah_list)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tambah_warga_btn = QtGui.QPushButton(self.tab)
        self.tambah_warga_btn.setObjectName(_fromUtf8("tambah_warga_btn"))
        self.verticalLayout_2.addWidget(self.tambah_warga_btn)
        self.edit_warga_btn = QtGui.QPushButton(self.tab)
        self.edit_warga_btn.setObjectName(_fromUtf8("edit_warga_btn"))
        self.verticalLayout_2.addWidget(self.edit_warga_btn)
        self.hapus_warga_btn = QtGui.QPushButton(self.tab)
        self.hapus_warga_btn.setObjectName(_fromUtf8("hapus_warga_btn"))
        self.verticalLayout_2.addWidget(self.hapus_warga_btn)
        self.ganti_pin = QtGui.QPushButton(self.tab)
        self.ganti_pin.setObjectName(_fromUtf8("ganti_pin"))
        self.verticalLayout_2.addWidget(self.ganti_pin)
        self.ganti_kartu = QtGui.QPushButton(self.tab)
        self.ganti_kartu.setObjectName(_fromUtf8("ganti_kartu"))
        self.verticalLayout_2.addWidget(self.ganti_kartu)
        self.hapus_semua_warga_btn = QtGui.QPushButton(self.tab)
        self.hapus_semua_warga_btn.setObjectName(_fromUtf8("hapus_semua_warga_btn"))
        self.verticalLayout_2.addWidget(self.hapus_semua_warga_btn)
        self.download_warga_btn = QtGui.QPushButton(self.tab)
        self.download_warga_btn.setObjectName(_fromUtf8("download_warga_btn"))
        self.verticalLayout_2.addWidget(self.download_warga_btn)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        TabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.tab_2)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.username = QtGui.QLineEdit(self.tab_2)
        self.username.setObjectName(_fromUtf8("username"))
        self.horizontalLayout_2.addWidget(self.username)
        self.password = QtGui.QLineEdit(self.tab_2)
        self.password.setObjectName(_fromUtf8("password"))
        self.horizontalLayout_2.addWidget(self.password)
        self.active = QtGui.QCheckBox(self.tab_2)
        self.active.setObjectName(_fromUtf8("active"))
        self.horizontalLayout_2.addWidget(self.active)
        self.save_user_btn = QtGui.QPushButton(self.tab_2)
        self.save_user_btn.setObjectName(_fromUtf8("save_user_btn"))
        self.horizontalLayout_2.addWidget(self.save_user_btn)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.user_list = QtGui.QTableWidget(self.tab_2)
        self.user_list.setObjectName(_fromUtf8("user_list"))
        self.user_list.setColumnCount(0)
        self.user_list.setRowCount(0)
        self.verticalLayout_7.addWidget(self.user_list)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.edit_user_btn = QtGui.QPushButton(self.tab_2)
        self.edit_user_btn.setObjectName(_fromUtf8("edit_user_btn"))
        self.verticalLayout_3.addWidget(self.edit_user_btn)
        self.hapus_user_btn = QtGui.QPushButton(self.tab_2)
        self.hapus_user_btn.setObjectName(_fromUtf8("hapus_user_btn"))
        self.verticalLayout_3.addWidget(self.hapus_user_btn)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        TabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.tab_3)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.search_log = QtGui.QLineEdit(self.tab_3)
        self.search_log.setObjectName(_fromUtf8("search_log"))
        self.horizontalLayout_3.addWidget(self.search_log)
        self.pushButton_3 = QtGui.QPushButton(self.tab_3)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.log_list = QtGui.QTableWidget(self.tab_3)
        self.log_list.setObjectName(_fromUtf8("log_list"))
        self.log_list.setColumnCount(0)
        self.log_list.setRowCount(0)
        self.verticalLayout_5.addWidget(self.log_list)
        self.horizontalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.pushButton = QtGui.QPushButton(self.tab_3)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.verticalLayout_6.addWidget(self.pushButton)
        self.pushButton_2 = QtGui.QPushButton(self.tab_3)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.verticalLayout_6.addWidget(self.pushButton_2)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.horizontalLayout_6.addLayout(self.verticalLayout_6)
        TabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.tab_4)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.cari_log_isi_ulang = QtGui.QLineEdit(self.tab_4)
        self.cari_log_isi_ulang.setObjectName(_fromUtf8("cari_log_isi_ulang"))
        self.horizontalLayout_7.addWidget(self.cari_log_isi_ulang)
        self.cari_log_isi_ulang_btn = QtGui.QPushButton(self.tab_4)
        self.cari_log_isi_ulang_btn.setObjectName(_fromUtf8("cari_log_isi_ulang_btn"))
        self.horizontalLayout_7.addWidget(self.cari_log_isi_ulang_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.isi_ulang_log = QtGui.QTableWidget(self.tab_4)
        self.isi_ulang_log.setObjectName(_fromUtf8("isi_ulang_log"))
        self.isi_ulang_log.setColumnCount(0)
        self.isi_ulang_log.setRowCount(0)
        self.verticalLayout.addWidget(self.isi_ulang_log)
        self.horizontalLayout_8.addLayout(self.verticalLayout)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.download_log_isi_ulang_btn = QtGui.QPushButton(self.tab_4)
        self.download_log_isi_ulang_btn.setObjectName(_fromUtf8("download_log_isi_ulang_btn"))
        self.verticalLayout_9.addWidget(self.download_log_isi_ulang_btn)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem3)
        self.horizontalLayout_8.addLayout(self.verticalLayout_9)
        TabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.tab_5)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.cari_log_user = QtGui.QLineEdit(self.tab_5)
        self.cari_log_user.setObjectName(_fromUtf8("cari_log_user"))
        self.horizontalLayout_9.addWidget(self.cari_log_user)
        self.cari_log_user_btn = QtGui.QPushButton(self.tab_5)
        self.cari_log_user_btn.setObjectName(_fromUtf8("cari_log_user_btn"))
        self.horizontalLayout_9.addWidget(self.cari_log_user_btn)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.log_user = QtGui.QTableWidget(self.tab_5)
        self.log_user.setObjectName(_fromUtf8("log_user"))
        self.log_user.setColumnCount(0)
        self.log_user.setRowCount(0)
        self.verticalLayout_8.addWidget(self.log_user)
        self.horizontalLayout_10.addLayout(self.verticalLayout_8)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.download_log_user_btn = QtGui.QPushButton(self.tab_5)
        self.download_log_user_btn.setObjectName(_fromUtf8("download_log_user_btn"))
        self.verticalLayout_10.addWidget(self.download_log_user_btn)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem4)
        self.horizontalLayout_10.addLayout(self.verticalLayout_10)
        TabWidget.addTab(self.tab_5, _fromUtf8(""))

        self.retranslateUi(TabWidget)
        TabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TabWidget)

    def retranslateUi(self, TabWidget):
        TabWidget.setWindowTitle(_translate("TabWidget", "ADMIN ATM BERAS", None))
        self.cari_warga.setText(_translate("TabWidget", "CARI", None))
        self.tambah_warga_btn.setText(_translate("TabWidget", "TAMBAH", None))
        self.edit_warga_btn.setText(_translate("TabWidget", "EDIT", None))
        self.hapus_warga_btn.setText(_translate("TabWidget", "HAPUS", None))
        self.ganti_pin.setText(_translate("TabWidget", "GANTI PIN", None))
        self.ganti_kartu.setText(_translate("TabWidget", "GANTI KARTU", None))
        self.hapus_semua_warga_btn.setText(_translate("TabWidget", "HAPUS SEMUA", None))
        self.download_warga_btn.setText(_translate("TabWidget", "DOWNLOAD", None))
        TabWidget.setTabText(TabWidget.indexOf(self.tab), _translate("TabWidget", "PENERIMA", None))
        self.username.setPlaceholderText(_translate("TabWidget", "USERNAME", None))
        self.password.setPlaceholderText(_translate("TabWidget", "PASSWORD", None))
        self.active.setText(_translate("TabWidget", "AKTIF", None))
        self.save_user_btn.setText(_translate("TabWidget", "SIMPAN", None))
        self.edit_user_btn.setText(_translate("TabWidget", "EDIT", None))
        self.hapus_user_btn.setText(_translate("TabWidget", "HAPUS", None))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_2), _translate("TabWidget", "USER", None))
        self.pushButton_3.setText(_translate("TabWidget", "CARI", None))
        self.pushButton.setText(_translate("TabWidget", "DOWNLOAD LOG", None))
        self.pushButton_2.setText(_translate("TabWidget", "HAPUS LOG", None))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_3), _translate("TabWidget", "LOG TRANSAKSI", None))
        self.cari_log_isi_ulang_btn.setText(_translate("TabWidget", "CARI", None))
        self.download_log_isi_ulang_btn.setText(_translate("TabWidget", "DOWNLOAD LOG", None))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_4), _translate("TabWidget", "LOG ISI ULANG", None))
        self.cari_log_user_btn.setText(_translate("TabWidget", "CARI", None))
        self.download_log_user_btn.setText(_translate("TabWidget", "DOWNLOAD LOG", None))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_5), _translate("TabWidget", "LOG USER", None))

